### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by sindresorhus** [tastejs/meta#1]
All the cool kids are doing it.

http://tastejs.com/blog

Example: http://blog.getbootstrap.com

Could be a nice place to share announcements, a curation of the absolute best blog posts (not to much though), summary of discussions, etc.

I really like the medium.com article design. We should have something similar: https://medium.com/i-m-h-o/125a8658682c

Run on Jekyll.
## 

@passy said: 18px base font-size

**Comment by btford** [comment]
> Run on Jekyll.

Haven't used Jekyll, but it looks cool.

> 18px base font-size

Yes.

**Comment by ColinEberhardt** [comment]
+1 to this idea. PropertyCross is pretty young, but we have already had some good blog posts from end-users:

http://blog.trackabout.com/2013/03/05/propertycross-android-implementation-shootout/

Also a centralized place to announce ToDoMVC, PropertyCross, TasteApp releases would be good.

**Comment by addyosmani** [comment]
Do we want to just put together something quick and dirty for now? We increasingly need a place for Taste and TodoMVC posts. Do we want to do something that can also have user accounts or at least avatars to let us easily have PropertyCross and other teams post too?

**Comment by stephenplusplus** [comment]
I'll take a crack at throwing something together in the next few days. I'll report back with any progress!

**Comment by addyosmani** [comment]
I wouldn't mind us opting for a generic barebones Jekyll blog for now and working on the design over time.

I've personally found that blog content has better sharing stats overall than G+ posts alone or announcement tweets.

**Comment by sindresorhus** [comment]
Since we're all pretty busy I think we should go with a simple no-maintenance hosted solution.

Possible ones:
- http://www.squarespace.com/templates/?q=takk
- http://sindresorhus.roon.io/
- http://sindresorhus.postagon.com/53nqtz9gw

I prefer the first as it's not just blogging and we could build the whole site in it. The theme also looks good.

**Comment by paulmillr** [comment]
IMHO the Roon is the cleanest stuff out there, pretty neat and has iOS client etc, markdown.

**Comment by addyosmani** [comment]
100% agree @sindresorhus. Also +1 on Roon. very clean and easy to read.

**Comment by passy** [comment]
+1 on Roon.

**Comment by sindresorhus** [comment]
Done: http://tastejs.roon.io (credentials in the usual place)

Let's try it out and if we like it I'll buy us custom domain support so we can have it at tastejs.com/blog

@addyosmani can you add `tastejavascript@gmail.com` to the tastejs gravatar account so we can get a nice tastejs profile pic on the blog?

**Comment by passy** [comment]
Thanks, Sindre! :)

**Comment by addyosmani** [comment]
@sindresorhus Thanks for setting it up! I'll of course get the tastejs gravatar account hooked up.

**Comment by addyosmani** [comment]
Added to the account. I can't find the passwords to tastejavascript though :) Gravatar sent over an email to verify.

**Comment by addyosmani** [comment]
Okay. All setup.

**Comment by sindresorhus** [comment]
@addyosmani looks nice. Can't wait to get some beautiful text in there too ;)

**Comment by addyosmani** [comment]
I'm thinking first up will probably be the TodoMVC release post :)

Btw, does the content of these posts end up on roon or somewhere in static form that we can edit? I just ask in case it doesn't and we'd prefer a more boring Jekyll setup with one of the existing themes.

**Comment by stephenplusplus** [comment]
Just in case any of my initial stab is usable: https://github.com/tastejs/todomvc/issues/597 :)

**Comment by sindresorhus** [comment]
@addyosmani I agree. Yes, but it's markdown so we can always easily move it. They also have an Export button.

**Comment by ColinEberhardt** [comment]
This blog looks really cool, thanks @sindresorhus for setting it up!

I do have one small request ... currently the footer states that TasteJS is "A better JavaScript learning experience. Keeper of TodoMVC. Eater of popsicles."

Now that PropertyCross has joined Taste - can we update this text to reflect the wider remit? Perhaps making reference to TasteStack too?

If we find some text that everyone is happy with http://tastejs.com/ should be updated too.

I am close to a 1.3 release for PropertyCross, the code is there, just need to update the website / builds etc ...

https://github.com/tastejs/PropertyCross/issues?labels=&milestone=4&page=1&state=open

There have been new frameworks added, Delphi and Lavaca, and some other frameworks have been updated to reflect the new iOS 7 flat style. I'd love to be able to blog about this release on the taste blog ;-)

**Comment by addyosmani** [comment]
Absolutely. We should get the homepage updated to include both
PropertyCross and TodoMVC logos too with links to respective repos.

Colin, we should get you access to TasteJS blog so you can announce or
cross-post about your release there.

**Comment by sindresorhus** [comment]
@ColinEberhardt was planning to way back, but totally slipped my mind, updated Twitter/Blog, will update the site later.

**Comment by ColinEberhardt** [comment]
@sindresorhus @addyosmani thanks :-)

**Comment by sindresorhus** [comment]
So, we should evaluate if we want to continue using Roon.io. If so I'll buy the custom domain package so we can have blog.tastejs.com or tastejs.com/blog.

@ColinEberhardt @mrpotes try writing your post using it and let us know what you think.

**Comment by ColinEberhardt** [comment]
OK, so I think roon.io is a decent platform - nice and simple.

The only thing I worry about is discoverability. The PropertyCross, TodoMVC and TasteJS sites all feel quite isolated. As a result, I do wonder how often people will read the blog!

As TasteJS is the central hub, it would help if it aggregated some of the data from the (currently) two sub projects. TasteJS is a lively project, but this is not reflected by the 'hub'!

It would be great if we could add links to the latest blog posts, or repo stats (e.g. number of PropertyCross apps, or TodoMVC apps), etc ...

**Comment by addyosmani** [comment]
I agree with everything above. I think at the very minimum we could improve the homepage to reflect the projects contained in TasteJS and better highlight the blog. I probably won't be able to get around to this until later next week, but if someone else wants to take a stab at this:
- Maybe split the homepage into two columns - monster on the left, new content on the right
- Right column contains three rows - an icon/section for TodoMVC, PropertyCross and a section with avatars for the team. You could probably steal this from the TodoMVC footer.
- Top navigation maybe? Contains links to the blog and other relevant places - Twitter account?

**Comment by sindresorhus** [comment]
We've decided to keep using roon.io. Now we need to plan what publish on the blog https://github.com/tastejs/watercooler/issues/10
