### ISSUE TITLE
taste.json metadata provided by framework authors.

### ISSUE THREAD

**Issue by dylang** [tastejs/meta#2]
As a framework owner, I have a `taste.json` file in my root directory that can be used by tastejs to provide content for the site.

Hypothetical taste.json example:

``` json
{
   "homepage": "http://angularjs.org/",
   "documentation": "http://docs.angularjs.org",
   "tutorials": {  
      "hello_world": "http://docs.angularjs.org/tutorial"
   },
   "api": "http://docs.angularjs.org/api/",
   "examples":  "http://angularjs.org/examples.json",
}
```

Other top-level values could include:
- IRC room
- Email list/Google Group
- StackExchange tag
- Plugin sites
- Twitter/AppNet ids
- Links to docs like changelog, goals, important blog posts
- Feature enums for generating comparison checklists
- Screenshots
- Demos
- Issues

Values are always urls. If the url ends in `.json` then it is assumed that is a file or api endpoint for additional data, such as a dynamically generated list of examples.

**Comment by sindresorhus** [comment]
It's a good idea, but I don't think it's very feasible as framework authors aren't interested in having yet another meta file and we want to have some control on what's shown on our site. I would rather see this kind of files hosted in one of our repos.

**Comment by passy** [comment]
Yap, having those is certainly a good idea. @stephenplusplus is already managing something similar for the revamped homepage: https://github.com/stephenplusplus/todomvc/blob/d0c419caeb5998cefe81d4b20cf46e4b1fbe9d5b/learn.json

I agree though that imposing this as another burden to framework authors probably won't work.

**Comment by dylang** [comment]
Good point, I hadn't considered that framework authors wouldn't want to maintain this file.

I was thinking the reason they would want to do this is it becomes a way for framework authors to promote and proselytize their work, keep links on third-party sites updated, and an entry point for new frameworks to be noticed by tastejs ("Just publish your taste.json and it will be added to the index.").

My overall goal is to distribute the burden of collecting and updating information across the framework maintainers and their contributors. There will likely be more of them than tastejs contributors.

I also imagined this file wouldn't be limited to frameworks like Angular or Backbone, but would also be useful for plugins and modules. It's like package.json for humans. But that's a stretch goal if this concept is accepted.

Perhaps I should have proposed this with less fields so it didn't seem to intimidating.

**Comment by sindresorhus** [comment]
> My overall goal is to distribute the burden of collecting and updating information across the framework maintainers and their contributors. There will likely be more of them than tastejs contributors.

We can still do that while keeping it in-house. Maintainers can easily submit PRs to keep it up to date. It's just that we're having a hard enough time convincing lazy framework authors to include a bower.json file.

But that's just my point of view. Let's hear from more people ;)

**Comment by addyosmani** [comment]
I actually don't think this is a bad idea, but as Sindre mentioned it's more realistic for us to maintain these in-house. It's hard enough getting framework authors to support things like Bower these days :) This type of meta-data might be useful for the changes @stephenplusplus has been suggesting for the main TodoMVC site.

**Comment by ColinEberhardt** [comment]
With PropertyCross we have a similar need for meta-data. Currently we use Jekyll for our website, and have meta-data associated with the 'post' that generates the page for each framework. Here's an example:

https://raw.github.com/ColinEberhardt/PropertyCross/master/website/_posts/2012-12-18-jquery-mobile.md

This will generate the table on the front page, contributors with avatars, the pie chart, download links etc ...

We also have a build system to generate the ~100 different app icons that PropertyCross uses!
