### ISSUE TITLE
Find a language neutral name

### ISSUE THREAD

**Issue by passy** [tastejs/meta#4]
As discussed with @addyosmani, @ColinEberhardt and @godds the name TasteJS gives the impression that we would limit submissions only to JavaScript. Can we find a name that is more welcoming to non-JS solutions, preferably with an available TLD? :)

/cc @sindresorhus

**Comment by stephenplusplus** [comment]
What other solutions will there be? Non-JS as in CoffeeScript, TypeScript, etc. or as in "wont-compile-to-JS-ever" languages?

**Comment by passy** [comment]
@stephenplusplus The guys from [propertycross](http://propertycross.com/) already have apps that fall into the "wont-compile-to-JS-ever" category like Adobe AIR and Mono/Xamarin and as we progress with with TasteStack and get some backend solutions, those could also include non-JS languages.

**Comment by stephenplusplus** [comment]
I'm still trying to piece together what this Taste thing is, thanks for filling in some blanks :)

TasteStack is kind of a cool, all-encompassing name in itself. And the .com is still available!

**Comment by ColinEberhardt** [comment]
Just for reference, with PropertyCross, we wanted this project to focus on comparing frameworks for cross-platform mobile application development. Of course, there are a lot of HTML5 frameworks designed for this purpose, but there are also many non-JS frameworks.

Some examples include, Xamarin (C#), Embarcadero (Delphi), MoSync (C++), Marmalade, Corona, Strawberry ... and many many more!

There has been a lot of talk recently about the UX compromises you make by choosing a HTML5 framework for cross-platfrom mobile. For this reason we consider it very important that PropertyCross includes the non-JS frameworks, especially those that deliver fully native UIs.

**Comment by passy** [comment]
@stephenplusplus I like the term TasteStack, too. We would certainly have to rename the corresponding project to avoid confusion, but  now is probably a good time for that.

**Comment by sindresorhus** [comment]
I don't see it necessary to switch name. While it's true that we have non-js stuff in the org it's also true that everything is compared against at least one JS implementation. I think the current name stands for exactly where we want to be; A complete solution for comparing front-end web JS solutions with everything else.

**Comment by addyosmani** [comment]
To be clear, TasteStack is already a TasteJS sub-project with the goal of enabling developers to compare different end to end stack solutions. If we opted for that I worry that it might cause a little bit of confusion. My current preferences are TasteJS or Taste, however the latter would make it really really hard for us to make wins on SEO and discoverability. We do need to keep this in mind :)

**Comment by ColinEberhardt** [comment]
I am not too concerned about the 'JS' suffix on the overall organization name. Going forwards, I am sure that around 1/3 of all PropertyCross implementations will not be JavaScript-based / hybrid apps. There are numerous cross-compiler solutions out there, and we would certainly like to include them.

However, as PropertyCross will retain its on identity, I don't think the fact that the overarching organisation is a little more JavaScript-focused will be an issue at all.

All I really wanted to hear is that the TasteJS team are open to non JavaScript technologies. Which, from our call, it sounds like you all are!

**Comment by sindresorhus** [comment]
> All I really wanted to hear is that the TasteJS team are open to non JavaScript technologies. Which, from our call, it sounds like you all are!

We absolutely are :)
