### ISSUE TITLE
Generator Tie-In

### ISSUE THREAD

**Issue by stephenplusplus** [tastejs/meta#5]
``` bash
$ yo taste
# ascii taste monster
What framework are you interested in? angular

# fetches angular demonstration

# ascii popsicle
All set!
```

It could pop it in `/demonstrations/angular` to enable using a sub-generator to include other demonstrations alongside.

**Comment by sindresorhus** [comment]
I've had this thought too, and I think it would be a handy way for people to quickly fetch and try out our different demo apps.

Maybe consider using the canonical name for consistency? `yo tastejs`

**Comment by passy** [comment]
I like it! Could we use a bundled or remotely fetched `learn.json` to resolve the names?

**Comment by sindresorhus** [comment]
Remote fetch it

**Comment by addyosmani** [comment]
Related, but I could just throw together a generator-todomvc that does something similar for that sub-project. On that note..I just realized we don't actually have a generator for TodoMVC apps (ones people want to create from scratch). I mean, we've got a boilerplate already but who knows. Maybe it would be useful.

**Comment by passy** [comment]
Right, I don't think there's a good reason why this should not exist.

**Comment by sindresorhus** [comment]
Oops, it should of course be `yo todomvc <framework>`.

**Comment by sindresorhus** [comment]
Seems like we're all too busy for this. Maybe we should have `@yeoman` on twitter ask if anyone would be interested in doing it?

**Comment by arthurvr** [comment]
> On that note..I just realized we don't actually have a generator for TodoMVC apps (ones people want to create from scratch). I mean, we've got a boilerplate already but who knows. Maybe it would be useful.

@addyosmani Ha! I had that one locally for months and never finished it :) Will see if I can update it to latest version and publish this evening.

**Comment by addyosmani** [comment]
Hah! That's awesome :) Like minds!

**Comment by stephenplusplus** [comment]
This will be awesome!

**Comment by arthurvr** [comment]
> On that note..I just realized we don't actually have a generator for TodoMVC apps (ones people want to create from scratch). I mean, we've got a boilerplate already but who knows. Maybe it would be useful.

Up and running at https://github.com/arthurvr/generator-todomvc-app. Need to npm publish it but gonna do that shortly.

When I find the time, I'll work on the `yo todomvc` thingy as well.
