### ISSUE TITLE
ToDoMVC - make it easier to determine why an implementation isn't spec compliant

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/meta#6]
I was just looking through the ToDoMVC list (learning about Dojo!) and it struck me that it isn't terribly obvious why some implementation are not spec compliant.

Firstly, a minor point ... take Kendo UI for example, I think the colouring of the various implementations on the todomvc.com website is a little unclear. I find maroon to be quite an ambiguous colour! Is Kendo spec compliant or not?!

Now that I have determined that it is not spec compliant, I'd really like to have an easy way to find out why, so that I can consider fixing the outstanding issues and contributing my changes.

I looked through the issues, but must admit, I am not 100% sure where it falls short!

A method we use in PropertyCross, which I quite like, is to provide a direct link to the known issues for each framework, for example ...

http://propertycross.com/enyo/

We still need to do a bit more work on tightening-up the specification, but at least this does give would-be contributors an easy way to see how they might help.

**Comment by addyosmani** [comment]
One potential solution to this problem is introducing better labelling or a legend for the application implementation state. Rather than just being red or gray we could color them according to how close they are to being complete. Alternatively a percentage could be used to denote completeness.
