### ISSUE TITLE
PropertyCross v1.3 has been released

### ISSUE THREAD

**Issue by ColinEberhardt** [tastejs/meta#8]
After a little bit of inactivity (my bad, too many projects on the go), we have pushed out a v1.3 release:
- Delphi implementation added.
- Emy implementation added.
- Intel App Framework, Sencha Touch 2, Enyo and PhoneJS implementations updated.
- PhoneGap implementations now using common Cordova 3.1 configuration

A big thank you to @mrpotes who did _all_ the hard work on this one.

**Comment by sindresorhus** [comment]
Awesome. Would either of you be able to do a short write-up that we could post on the blog? http://tastejs.roon.io

**Comment by ColinEberhardt** [comment]
Sure - I'll sort something out, and also add a post about the automated tests for TodoMVC.

On that subject, I think the blog needs to be made more visible. @addyosmani asked me to add a blog post and I couldn't actually find its URL!

How about adding to tastejs.com somewhere? We should probably also link to the blog from todomvc.com and propertycross.com

Also - another minor point, from tastejs.com it took me a while to realise that the popsicle eating monster was the link to github! (Yeah, perhaps i am just a bit dense), anyhow, it might be worth adding a more conventional link to github.

**Comment by mrpotes** [comment]
You're not alone with the popsicle thing - initially I thought "oh, is that it?"

**Comment by sindresorhus** [comment]
> On that subject, I think the blog needs to be made more visible. @addyosmani asked me to add a blog post and I couldn't actually find its URL!

I agree. We decided we were going to do something about that but forgot.

> How about adding to tastejs.com somewhere? We should probably also link to the blog from todomvc.com and propertycross.com

I tweaked the tastejs site and added a link to the blog from it and the todomvc site. Please do with the propertycross site too.

**Comment by ColinEberhardt** [comment]
> I tweaked the tastejs site and added a link to the blog from it and the todomvc site. Please do with the propertycross site too.

That looks much better in my opinion. Thanks.

I've added some similar links from the PropertyCross site https://github.com/ColinEberhardt/PropertyCross-Site/commit/3ff750b20eff9c864aa9ab1cb409cdf51cfe3848

**Comment by ColinEberhardt** [comment]
Blogged: http://tastejs.roon.io/propertycross-1-3 :-)
